# Generated by Django 3.0 on 2020-03-21 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20200321_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='title',
            field=models.CharField(choices=[('P', 'Programming'), ('W', 'Web development'), ('H', 'Hacking'), ('E', 'Electrical Engineering'), ('EX', 'Electronic Engineering'), ('A', 'Android Development'), ('M', 'Machine Learning'), ('B', 'Bug bounty'), ('O', 'others')], max_length=3),
        ),
    ]
