# Generated by Django 3.0 on 2020-03-21 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_auto_20200321_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='title',
            field=models.CharField(choices=[('Programming', 'Programming'), ('Web development', 'Web development'), ('Hacking', 'Hacking'), ('Electrical Engineering', 'Electrical Engineering'), ('Electronic Engineering', 'Electronic Engineering'), ('Android Development', 'Android Development'), ('Machine Learning', 'Machine Learning'), ('Bug bounty', 'Bug bounty'), ('others', 'others')], max_length=100),
        ),
    ]
