# Generated by Django 3.0.4 on 2020-03-21 18:49

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_auto_20200321_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='questions',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
