# Generated by Django 3.0 on 2020-03-08 18:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200308_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='reply_to',
        ),
        migrations.AlterField(
            model_name='posts',
            name='date_post',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 8, 18, 0, 52, 3168, tzinfo=utc)),
        ),
    ]
