# Generated by Django 3.0 on 2020-03-08 18:19

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200308_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='reply_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Comments'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='date_post',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 8, 18, 19, 39, 235112, tzinfo=utc)),
        ),
    ]
