# Generated by Django 3.0 on 2020-03-09 09:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200309_0717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='date_post',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 9, 9, 12, 41, 996946, tzinfo=utc)),
        ),
    ]
