# Generated by Django 3.0 on 2020-03-12 21:42

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200309_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='posts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.Posts'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='date_post',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 12, 21, 42, 56, 80967, tzinfo=utc)),
        ),
    ]
