# Generated by Django 3.0 on 2020-03-14 18:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200312_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='date_post',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 14, 18, 21, 51, 207748, tzinfo=utc)),
        ),
    ]
