# Generated by Django 3.0 on 2020-03-21 12:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200314_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='date_post',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 21, 12, 22, 8, 911717, tzinfo=utc)),
        ),
    ]
