# Generated by Django 3.0.4 on 2020-03-21 18:49

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20200321_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='posts',
            name='subject',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
